name: PluginRodjao
version: 1.0
main: com.rodjao.me.Main
commands:
  sethome:
    description: Define a posição da casa do jogador
    usage: /sethome
  telhome:
    description: Teleporta o jogador para a sua casa
    usage: /tellhouse
